### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by bascrezee** [MeteoSwiss/grixraz#16]
Data:   Hourly files of FGSURF and ANASURF from KENDA-1 for JJA2023
Computation: (FGSURF-FGANA).groupby('valid_time.hour').mean()

| Stage  | open_mfdataset_noindexing | open_mfdataset_indexing | grixraz |
|----------|----------|----------|----------|
| referencing+lazy_loading | 1m48s;2m08s | 1m58s (2m24s) |  2m08s |
| reading+computing | (no reading) 1m58s |  (no reading) 1m53s | 2.9s |

**Comment by frazane** [comment]
Latest benchmarks put directly in the ppt slide for the kachathon 👍
